# Tutorial

# C++(5)：语句和函数

在高级编程语言中，语句和函数是最基本的单位。C++中大部分的语句同C语言中一致，如顺序结构、选择结构和循环结构等。在此基础上C++又新增加了一些新的功能，如try-catch语句处理运行时出现的异常行为。

## 一. Try语句块和异常处理

所谓异常，通常指程序在运行时发生的一些未定义的、超出了程序正常功能的现象。如果某个程序在运行时出现了异常，则表明程序出现了不应有的故障，无法继续执行。此时应当对这种情况进行专门处理，否则程序极可能出现严重问题，比如崩溃掉。

程序的异常处理通常包括异常的检测和处理两部分。在C++中提供了一下方法来处理与运行时异常相关的问题：

- **throw表达式**：在遇到问题时，可以使用throw表达式人为地抛出一个异常，表示遇到了无法处理的问题。
- **try语句块**：try语句块以关键字try开始，以若干个catch子句结束。try中抛出的异常通常会被某一个catch处理，因此catch语句通常也被称作异常处理代码exception handler。 
- **异常类**：用于表示异常的具体信息。

### 1. throw表达式

throw表达式包括throw关键字和其后的表示异常类型的表达式。通常通过这种方式构成一个throw语句。

例如，假设我们在程序中的逻辑规定，某两个值不能相等，否则程序将会产生错误，那么可以采用以下方式：

	if (num1 == num2)
	{
		throw runtime_error("Num1 should not be equal to Num2.");
	}

当执行抛出异常语句时，当前函数将终止，并将程序控制权转移给处理该异常的代码。类型runtime_error是C++提供的一种标准异常类型，定义在stdexcpt头文件中。

### 2. try语句块

try语句块包括try关键字加后面紧跟的一个语句块。在try语句块之后是一个或多个catch子句，每个catch子句包括三部分：关键字catch、异常声明和catch语句块。当选中某个catch子句处理异常后，程序跳转到最后一个catch子句的后面继续向下执行。

通常try语句块的形式如：

	try
	{
		//产生异常的代码
	}
	catch (exception-declaration1)
	{
		//异常处理1
	}
	catch (exception-declaration2)
	{
		//异常处理2
	}

